;;; -*- mode: Lisp; indent-tabs-mode: nil; -*-
;;;
;;; Copyright (c) 2010, Alexander Gavrilov (angavrilov@gmail.com)
;;;
;;; This file defines a package for all SSE intrinsics.
;;;

#+ecl
(eval-when (:load-toplevel)
  (require 'cmp))

#+sbcl
(pushnew :SSE2 *features*)

(defpackage #:SSE
  #+sbcl
  (:use #:COMMON-LISP #:SB-C #:SB-VM #:SB-INT #:SB-KERNEL #:SB-ASSEM #:SB-EXT #:SB-SYS)
  #+sbcl
  (:import-from #:SB-VM
                #:SINGLE-REG #:DOUBLE-REG
                #:INT-SSE-REG #:SINGLE-SSE-REG #:DOUBLE-SSE-REG #:SSE-REG
                #:INT-SSE-STACK #:SINGLE-SSE-STACK #:DOUBLE-SSE-STACK
                #:INT-SSE-IMMEDIATE #:SINGLE-SSE-IMMEDIATE #:DOUBLE-SSE-IMMEDIATE
                #:SIGNED-REG #:SIGNED-STACK #:UNSIGNED-REG #:UNSIGNED-STACK
                #:SIGNED-NUM #:UNSIGNED-NUM #:UNTAGGED-NUM #:IMMEDIATE
                #:SAP-REG #:DESCRIPTOR-REG #:ANY-REG #:TAGGED-NUM
                #:RAX-OFFSET #:RDI-OFFSET #:RBP-TN #:FRAME-BYTE-OFFSET
                #:MAKE-EA #:REG-IN-SIZE #:LOADW)
  #+sbcl
  (:import-from #:SB-C
                #:SPLICE-FUN-ARGS #:EXTRACT-FUN-ARGS
                #:%DEFTRANSFORM #:DX-SAFE
                #:GIVE-UP-IR1-TRANSFORM #:ABORT-IR1-TRANSFORM
                #:INSERT-ARRAY-BOUNDS-CHECKS #:VECTOR-LENGTH
                #:ASSERT-ARRAY-RANK #:ASSERT-LVAR-TYPE
                #:CONSTANT-LVAR-P #:LVAR-VALUE #:LVAR-TYPE #:LVAR-USES
                #:LVAR-FUN-NAME #:BASIC-COMBINATION-FUN
                #:LEXENV-POLICY #:NODE-LEXENV #:POLICY
                #:CAST-P #:CAST-VALUE #:DELETE-FILTER
                #:FIND-SAETP #:FIND-SAETP-BY-CTYPE)
  #+sbcl
  (:import-from #:SB-IMPL
                #:%ARRAY-ROW-MAJOR-INDEX)
  #+sbcl
  (:shadow #:INT-SSE-PACK #:FLOAT-SSE-PACK #:DOUBLE-SSE-PACK #:DEFKNOWN)
  #+ecl
  (:use #:COMMON-LISP #:FFI)
  #+ecl
  (:import-from #:EXT
                #:INT-SSE-PACK #:FLOAT-SSE-PACK #:DOUBLE-SSE-PACK
                #:SSE-PACK-P #:ARRAY-ELEMENT-TYPE-BYTE-SIZE
                #:*SSE-PACK-PRINT-MODE*)
  #+ecl
  (:shadow #:SSE-PACK)
  ;; Common exports:
  (:export #:SSE-PACK #:SSE-PACK-P
           #:INT-SSE-PACK #:FLOAT-SSE-PACK #:DOUBLE-SSE-PACK
           #:*SSE-PACK-PRINT-MODE*
           #:SSE-ARRAY #:MAKE-SSE-ARRAY
           #:0.0-PS #:TRUE-SS #:FALSE-SS #:TRUE-PS #:FALSE-PS
           #:SET1-PS #:SET-PS #:SETR-PS #:SETZERO-PS
           #:0.0-PD #:TRUE-SD #:FALSE-SD #:TRUE-PD #:FALSE-PD
           #:SET1-PD #:SET-PD #:SETR-PD #:SETZERO-PD
           #:0-PI #:TRUE-PI #:FALSE-PI #:SETZERO-PI
           #:CPU-MXCSR #:CPU-MXCSR-BITS #:WITH-SAVED-MXCSR #:CPU-CONFIGURE-ROUNDING)
  #+sbcl
  (:export :/<-PD :/<-PS :/<-SD :/<-SS :/<=-PD :/<=-PS :/<=-SD :/<=-SS :/=-PD :/=-PI16 :/=-PI32 :/=-PI8 :/=-PS :/=-SD :/=-SD?
           :/=-SDU? :/=-SS :/=-SS? :/=-SSU? :/>-PD :/>-PS :/>-SD :/>-SS :/>=-PD :/>=-PS :/>=-SD :/>=-SS :<-PD :<-PI16 :<-PI32
           :<-PI8 :<-PS :<-SD :<-SD? :<-SDU? :<-SS :<-SS? :<-SSU? :<=-PD :<=-PI16 :<=-PI32 :<=-PI8 :<=-PS :<=-SD :<=-SD?
           :<=-SDU? :<=-SS :<=-SS? :<=-SSU? :=-PD :=-PI16 :=-PI32 :=-PI64 :=-PI8 :=-PS :=-SD :=-SD? :=-SDU? :=-SS :=-SS?
           :=-SSU? :>-PD :>-PI16 :>-PI32 :>-PI64 :>-PI8 :>-PS :>-SD :>-SD? :>-SDU? :>-SS :>-SS? :>-SSU? :>=-PD :>=-PI16
           :>=-PI32 :>=-PI8 :>=-PS :>=-SD :>=-SD? :>=-SDU? :>=-SS :>=-SS? :>=-SSU? :ABS-PI16 :ABS-PI32 :ABS-PI8 :ADD-PD
           :ADD-PI16 :ADD-PI32 :ADD-PI64 :ADD-PI8 :ADD-PS :ADD-SD :ADD-SS :ADDS-PI16 :ADDS-PI8 :ADDS-PU16 :ADDS-PU8 :ADDSUB-PD
           :ADDSUB-PS :ALIGNR-PI8 :AND-PD :AND-PI :AND-PS :ANDNOT-PD :ANDNOT-PI :ANDNOT-PS :AREF-APD :AREF-API :AREF-APS
           :AREF-CLFLUSH :AREF-PD :AREF-PI :AREF-PREFETCH-NTA :AREF-PREFETCH-T0 :AREF-PREFETCH-T1 :AREF-PREFETCH-T2 :AREF-PS
           :AREF-SD :AREF-SI64 :AREF-SPD :AREF-SPI :AREF-SPS :AREF-SS :AVG-PU16 :AVG-PU8 :BLEND-PD :BLEND-PI16 :BLEND-PS
           :BLENDV-PD :BLENDV-PI8 :BLENDV-PS :CMPORD-PD :CMPORD-PS :CMPORD-SD :CMPORD-SS :CMPUNORD-PD :CMPUNORD-PS
           :CMPUNORD-SD :CMPUNORD-SS :CONVERT-PD-TO-PI32 :CONVERT-PD-TO-PS :CONVERT-PI-TO-SI32 :CONVERT-PI-TO-SI64
           :CONVERT-PI-TO-SU32 :CONVERT-PI-TO-SU64 :CONVERT-PI16-TO-PI32 :CONVERT-PI16-TO-PI64 :CONVERT-PI32-TO-PD
           :CONVERT-PI32-TO-PI64 :CONVERT-PI32-TO-PS :CONVERT-PI8-TO-PI16 :CONVERT-PI8-TO-PI32 :CONVERT-PI8-TO-PI64
           :CONVERT-PS-TO-PD :CONVERT-PS-TO-PI32 :CONVERT-PU16-TO-PI32 :CONVERT-PU16-TO-PI64 :CONVERT-PU32-TO-PI64
           :CONVERT-PU8-TO-PI16 :CONVERT-PU8-TO-PI32 :CONVERT-PU8-TO-PI64 :CONVERT-SD-TO-SI32 :CONVERT-SD-TO-SI64
           :CONVERT-SD-TO-SS :CONVERT-SI32-TO-PI :CONVERT-SI32-TO-SD :CONVERT-SI32-TO-SS :CONVERT-SI64-TO-PI
           :CONVERT-SI64-TO-SD :CONVERT-SI64-TO-SS :CONVERT-SS-TO-SD :CONVERT-SS-TO-SI32 :CONVERT-SS-TO-SI64
           :CONVERT-SU32-TO-PI :CONVERT-SU64-TO-PI :CPU-CLFLUSH :CPU-LOAD-FENCE :CPU-MEMORY-FENCE :CPU-PAUSE :CPU-PREFETCH-NTA
           :CPU-PREFETCH-T0 :CPU-PREFETCH-T1 :CPU-PREFETCH-T2 :CPU-STORE-FENCE :DIV-PD :DIV-PS :DIV-SD :DIV-SS :DP-PD :DP-PS
           :EXTRACT-PI16 :HADD-PD :HADD-PI16 :HADD-PI32 :HADD-PS :HADDS-PI16 :HSUB-PD :HSUB-PI16 :HSUB-PI32 :HSUB-PS
           :HSUBS-PI16 :IF-PD :IF-PI :IF-PS :INSERT-PI16 :INSERT-PI32 :INSERT-PI8 :LOADH-PD :LOADL-PD :MADD-PI16 :MADDUBS-PI16
           :MASKMOVEU-PI :MAX-PD :MAX-PI16 :MAX-PI32 :MAX-PI8 :MAX-PS :MAX-PU16 :MAX-PU32 :MAX-PU8 :MAX-SD :MAX-SS
           :MEM-REF-APD :MEM-REF-API :MEM-REF-APS :MEM-REF-PD :MEM-REF-PI :MEM-REF-PS :MEM-REF-SD :MEM-REF-SI64 :MEM-REF-SS
           :MEM-REF-STREAMING :MIN-PD :MIN-PI16 :MIN-PI32 :MIN-PI8 :MIN-PS :MIN-PU16 :MIN-PU32 :MIN-PU8 :MIN-SD :MIN-SS
           :MINPOS-PU16 :MOVE-PI64 :MOVE-SD :MOVE-SS :MOVEDUP-PD :MOVEHDUP-PS :MOVEHL-PS :MOVELDUP-PS :MOVELH-PS :MOVEMASK-PD
           :MOVEMASK-PI8 :MOVEMASK-PS :MPSAD-PU8 :MUL-PD :MUL-PI32 :MUL-PS :MUL-PU32 :MUL-SD :MUL-SS :MULHI-PI16 :MULHI-PU16
           :MULHRS-PI16 :MULLO-PI16 :MULLO-PI32 :NEG-PD :NEG-PI16 :NEG-PI32 :NEG-PI64 :NEG-PI8 :NEG-PS :NEG-SD :NEG-SS :NOT-PD
           :NOT-PI :NOT-PS :OR-PD :OR-PI :OR-PS :PACKS-PI16 :PACKS-PI32 :PACKU16-PI32 :PACKUS-PI16 :PACKUS-PI32 :RCP-PS
           :RCP-SS :ROUND-PD :ROUND-PS :ROUND-SD :ROUND-SS :ROW-MAJOR-AREF-APD :ROW-MAJOR-AREF-API :ROW-MAJOR-AREF-APS
           :ROW-MAJOR-AREF-CLFLUSH :ROW-MAJOR-AREF-PD :ROW-MAJOR-AREF-PI :ROW-MAJOR-AREF-PREFETCH-NTA
           :ROW-MAJOR-AREF-PREFETCH-T0 :ROW-MAJOR-AREF-PREFETCH-T1 :ROW-MAJOR-AREF-PREFETCH-T2 :ROW-MAJOR-AREF-PS
           :ROW-MAJOR-AREF-SD :ROW-MAJOR-AREF-SI64 :ROW-MAJOR-AREF-SPD :ROW-MAJOR-AREF-SPI :ROW-MAJOR-AREF-SPS
           :ROW-MAJOR-AREF-SS :RSQRT-PS :RSQRT-SS :SAD-PU8 :SET-PI16 :SET-PI32 :SET-PI64 :SET-PI8 :SET-PU32 :SET-PU64 :SET-SD
           :SET-SS :SET1-PI16 :SET1-PI32 :SET1-PI64 :SET1-PI8 :SET1-PU32 :SET1-PU64 :SETR-PI16 :SETR-PI32 :SETR-PI64 :SETR-PI8
           :SETR-PU32 :SETR-PU64 :SHUFFLE-PD :SHUFFLE-PI32 :SHUFFLE-PI8 :SHUFFLE-PS :SHUFFLEHI-PI16 :SHUFFLELO-PI16 :SIGN-PI16
           :SIGN-PI32 :SIGN-PI8 :SLL-PI16 :SLL-PI32 :SLL-PI64 :SLLI-PI :SLLI-PI16 :SLLI-PI32 :SLLI-PI64 :SQRT-PD :SQRT-PS
           :SQRT-SD :SQRT-SS :SRA-PI16 :SRA-PI32 :SRAI-PI16 :SRAI-PI32 :SRL-PI16 :SRL-PI32 :SRL-PI64 :SRLI-PI :SRLI-PI16
           :SRLI-PI32 :SRLI-PI64 :STOREH-PD :STOREL-PD :STREAM-LOAD-PI :STREAM-PD :STREAM-PI :STREAM-PS :SUB-PD :SUB-PI16
           :SUB-PI32 :SUB-PI64 :SUB-PI8 :SUB-PS :SUB-SD :SUB-SS :SUBS-PI16 :SUBS-PI8 :SUBS-PU16 :SUBS-PU8 :TRUNCATE-PD-TO-PI32
           :TRUNCATE-PS-TO-PI32 :TRUNCATE-SD-TO-SI32 :TRUNCATE-SD-TO-SI64 :TRUNCATE-SS-TO-SI32 :TRUNCATE-SS-TO-SI64
           :UNPACKHI-PD :UNPACKHI-PI16 :UNPACKHI-PI32 :UNPACKHI-PI64 :UNPACKHI-PI8 :UNPACKHI-PS :UNPACKLO-PD :UNPACKLO-PI16
           :UNPACKLO-PI32 :UNPACKLO-PI64 :UNPACKLO-PI8 :UNPACKLO-PS :XOR-PD :XOR-PI :XOR-PS))

